import BlogReadingApp from "../BlogReadingApp";
import "./App.css";
import { useState } from "react";

const INITIAL_STATE = [
  {
    id: 1,
    title: "The Story of Lorem",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aliquam purus sit amet luctus venenatis lectus magna fringilla. Est ante in nibh mauris cursus mattis molestie a. Facilisis mauris sit amet massa vitae tortor. Volutpat odio facilisis mauris sit amet. Donec ultrices tincidunt arcu non sodales neque sodales. Tellus mauris a diam maecenas. Volutpat diam ut venenatis tellus in metus vulputate. Turpis cursus in hac habitasse platea dictumst quisque sagittis. Quam quisque id diam vel quam elementum. Aliquet nibh praesent tristique magna sit amet purus gravida. Sed pulvinar proin gravida hendrerit lectus. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean sed adipiscing diam donec adipiscing. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Interdum velit laoreet id donec ultrices tincidunt arcu non. In mollis nunc sed id semper risus in hendrerit. Orci porta non pulvinar neque laoreet suspendisse interdum. Dui sapien eget mi proin sed libero enim sed faucibus. Convallis posuere morbi leo urna molestie. Praesent tristique magna sit amet purus gravida quis blandit turpis. Venenatis cras sed felis eget velit. Tortor at auctor urna nunc. Pretium fusce id velit ut tortor. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Accumsan tortor posuere ac ut consequat. Egestas egestas fringilla phasellus faucibus scelerisque. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Euismod lacinia at quis risus sed. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien.",
  },
  {
    id: 2,
    title: "This is Just More Lorem",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ac feugiat sed lectus vestibulum mattis ullamcorper. Ut tellus elementum sagittis vitae et leo duis ut. Semper quis lectus nulla at volutpat. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus. Turpis massa tincidunt dui ut ornare lectus. Eros in cursus turpis massa tincidunt dui. Proin gravida hendrerit lectus a. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Cras ornare arcu dui vivamus arcu felis bibendum. Nisi quis eleifend quam adipiscing vitae proin sagittis nisl. Volutpat blandit aliquam etiam erat velit. Urna cursus eget nunc scelerisque viverra mauris in. Egestas dui id ornare arcu odio. Faucibus in ornare quam viverra orci sagittis eu volutpat. Consectetur libero id faucibus nisl. Scelerisque eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada. A cras semper auctor neque vitae. Ac auctor augue mauris augue neque. Neque aliquam vestibulum morbi blandit cursus risus at ultrices. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean sed adipiscing diam donec adipiscing. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Interdum velit laoreet id donec ultrices tincidunt arcu non. In mollis nunc sed id semper risus in hendrerit. Orci porta non pulvinar neque laoreet suspendisse interdum. Dui sapien eget mi proin sed libero enim sed faucibus. Convallis posuere morbi leo urna molestie. Praesent tristique magna sit amet purus gravida quis blandit turpis. Venenatis cras sed felis eget velit. Tortor at auctor urna nunc. Pretium fusce id velit ut tortor. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Accumsan tortor posuere ac ut consequat. Egestas egestas fringilla phasellus faucibus scelerisque. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Euismod lacinia at quis risus sed. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien.",
  },
  {
    id: 3,
    title: "Once Again We Use Lorem",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Et tortor consequat id porta nibh venenatis. Risus commodo viverra maecenas accumsan. A cras semper auctor neque vitae tempus quam pellentesque nec. Sem fringilla ut morbi tincidunt augue interdum velit. Praesent semper feugiat nibh sed pulvinar proin gravida. Eu scelerisque felis imperdiet proin fermentum. Eget nulla facilisi etiam dignissim diam quis enim lobortis. Ut diam quam nulla porttitor massa id neque aliquam vestibulum. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Sapien faucibus et molestie ac feugiat. Aenean vel elit scelerisque mauris pellentesque pulvinar. Augue lacus viverra vitae congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean sed adipiscing diam donec adipiscing. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Interdum velit laoreet id donec ultrices tincidunt arcu non. In mollis nunc sed id semper risus in hendrerit. Orci porta non pulvinar neque laoreet suspendisse interdum. Dui sapien eget mi proin sed libero enim sed faucibus. Convallis posuere morbi leo urna molestie. Praesent tristique magna sit amet purus gravida quis blandit turpis. Venenatis cras sed felis eget velit. Tortor at auctor urna nunc. Pretium fusce id velit ut tortor. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Accumsan tortor posuere ac ut consequat. Egestas egestas fringilla phasellus faucibus scelerisque. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Euismod lacinia at quis risus sed. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien.",
  },
  {
    id: 4,
    title: "This is Just More Lorem",
    body: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At augue eget arcu dictum varius duis at consectetur. Est ultricies integer quis auctor elit. Habitasse platea dictumst quisque sagittis purus sit. Varius duis at consectetur lorem donec massa sapien faucibus. Risus quis varius quam quisque id. Faucibus a pellentesque sit amet porttitor eget. Tempor orci eu lobortis elementum nibh tellus. Sociis natoque penatibus et magnis. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Gravida rutrum quisque non tellus orci ac auctor. Commodo viverra maecenas accumsan lacus vel facilisis volutpat. Condimentum mattis pellentesque id nibh tortor id aliquet. Morbi leo urna molestie at elementum. Mauris cursus mattis molestie a iaculis at erat pellentesque. Adipiscing elit duis tristique sollicitudin nibh. Facilisi morbi tempus iaculis urna id volutpat lacus laoreet non. Bibendum neque egestas congue quisque. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Aenean sed adipiscing diam donec adipiscing. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Suspendisse potenti nullam ac tortor vitae purus faucibus ornare suspendisse. Interdum velit laoreet id donec ultrices tincidunt arcu non. In mollis nunc sed id semper risus in hendrerit. Orci porta non pulvinar neque laoreet suspendisse interdum. Dui sapien eget mi proin sed libero enim sed faucibus. Convallis posuere morbi leo urna molestie. Praesent tristique magna sit amet purus gravida quis blandit turpis. Venenatis cras sed felis eget velit. Tortor at auctor urna nunc. Pretium fusce id velit ut tortor. Vulputate mi sit amet mauris commodo quis imperdiet massa tincidunt. Accumsan tortor posuere ac ut consequat. Egestas egestas fringilla phasellus faucibus scelerisque. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Euismod lacinia at quis risus sed. Commodo quis imperdiet massa tincidunt nunc pulvinar sapien.",
  },
];

function App() {
  const [blogs, setBlogs] = useState(INITIAL_STATE);
  const [activePost, setActivePost] = useState();

  return (
    <div className="App">
      <BlogReadingApp
        INITIAL_STATE={INITIAL_STATE}
        blogs={blogs}
        activePost={activePost}
        setActivePost={setActivePost}
      />
    </div>
  );
}

export default App;
